---
- name: install docker.io package
  ansible.builtin.package:
    name: docker.io
    state: present

- name: create vmselect container
  community.docker.docker_container:
    name: vmselect
    image: victoriametrics/vmselect:v1.125.0-cluster
    published_ports:
      - '{{ vmselect_port }}:{{ vmselect_port }}'
    restart_policy: always
    detach: yes
    command: >-
      {{ groups['vmstorage']
        | map('extract', hostvars)
        | map(attribute='inventory_hostname')
        | map('regex_replace', '^(.*)$', '--storageNode=\1:' + vmstorage_select_port)
      }}
