---
- name: install docker.io package
  ansible.builtin.package:
    name: docker.io
    state: present

- name: create /etc/victoriametrics folder
  ansible.builtin.file:
    path: /etc/victoriametrics
    state: directory
    owner: root
    group: root
    mode: '0755'

- ansible.builtin.import_tasks: tls.yaml

- name: create auth.yml file
  ansible.builtin.template:
    src: auth.yml.j2
    dest: /etc/victoriametrics/auth.yml
    owner: root
    group: root
    mode: '0600'
  notify: restart vmauth

- name: create vmauth container
  community.docker.docker_container:
    name: vmauth
    image: victoriametrics/vmauth:v1.125.0
    published_ports:
      - '{{ vmauth_port }}:{{ vmauth_port }}'
    volumes:
      - /etc/victoriametrics/auth.yml:/etc/victoriametrics/auth.yml
      - /etc/victoriametrics/vmauth.crt:/etc/victoriametrics/vmauth.crt:ro
      - /etc/victoriametrics/vmauth.key:/etc/victoriametrics/vmauth.key:ro
      - /etc/ssl/certs/vmgraf-ca.pem:/etc/ssl/certs/vmgraf-ca.pem:ro
    restart_policy: always
    detach: yes
    command:
      - '-tls'
      - '-tlsCertFile=/etc/victoriametrics/vmauth.crt'
      - '-tlsKeyFile=/etc/victoriametrics/vmauth.key'
      - '-auth.config=/etc/victoriametrics/auth.yml'
      - '-backend.TLSCAFile=/etc/ssl/certs/vmgraf-ca.pem'
